theme: jekyll-theme-slate

show_downloads: true

github:
  zip_url: https://github.com/mkschleg/Resampling.jl/archive/master.zip
  tar_url: https://github.com/mkschleg/Resampling.jl/archive/master.zip
  arxiv_url: https://arxiv.org/abs/1906.04328
